name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            path/output/bin/
            path/output/test-results
            !path/**/*.tmp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
