name: delivery
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
            name: my-artifact
            path: |
              path/output/bin/
              path/output/test-results
              !path/**/*.tmp
              

      - deploy:
          runs-on: ubuntu-latest
          needs: deliver
          steps:
            - uses: actions/download-artifact@v4
              with:
                 name: projetozipado.zip
            - name: Display structure of downloaded files
              run: ls -R
